const LOG_ACTION = {
  ACTION_CREATE: "CREATE",
  ACTION_UPDATE: "UPDATE",
  ACTION_DELETE: "DELETE",
  ACTION_FORCE_DELETE: "FORCE_DELETE",
  ACTION_REGISTED: "MEAL_REGISTED",
  ACTION_LOGIN: "LOGIN",
  ACTION_APPROVE: "APPROVE",
  ACTION_REJECT: "REJECT",
  ACTION_CANCEL: "CANCEL",
  ACTION_MARK_PAID: "MARK_PAID",
};

module.exports = LOG_ACTION;
