const NOTIFICATION_STATUS = {
  INACTIVE: "0",
  ACTIVE: "1",
};

const NOTIFICATION_TYPE = {
  LATE_REGISTRATION: "LATE_REGISTRATION",
  PAYMENT_DUE: "PAYMENT_DUE",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",
  APPROVAL: "APPROVAL",
  SYSTEM: "SYSTEM",
};

module.exports = {
  NOTIFICATION_STATUS,
  NOTIFICATION_TYPE,
};
